name: Demo Supply Chain Attack


on: [push]
jobs:
  simulate-attack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Malicious Action
        uses: mohammad-nayer/echo-secrets-action@7a32e023f4b069fe39ee0be68ca1c3dfc362edfe
